# nixpacks.toml

# Paksa Nixpacks untuk mengaktifkan provider PHP dan Python sekaligus
providers = ["php", "python"]

[phases.setup]
nixPkgs = ["...", "python3", "python3Packages.pip"]

[phases.install]
cmds = [
  "composer install --ignore-platform-reqs --no-dev --optimize-autoloader",
  "python3 -m pip install -r requirements.txt"
]